---
title: "Dan Negrey | Shiny - NFL Family Picks"
output:
    flexdashboard::flex_dashboard:
        theme: bootstrap
        orientation: rows
        css: www/styles.css
        logo: www/dan-icon.png
        favicon: www/dan-icon.png
        navbar:
            - {icon: "fa-globe", href: "https://dnegrey.com", target: "_blank"}
            - {icon: "fa-linkedin", href: "https://www.linkedin.com/in/dnegrey", target: "_blank"}
            - {icon: "fa-github", href: "https://github.com/dnegrey", target: "_blank"}
            - {icon: "fa-twitter", href: "https://twitter.com/negreydan", target: "_blank"}
            - {icon: "fa-envelope", href: "mailto:dnegrey@gmail.com"}
runtime: shiny
---

```{r global, include=FALSE}
source("src/R/util/sourceFunctions.R")
sourceFunctions("src/R/util")
sink(file = "/dev/null")
suppressMessages(loadPackages("etc/PACKAGES"))
sink()
sourceFunctions("src/R/app")
load("pub/main.RData")
addResourcePath(basename(getwd()), getwd())
```

Sidebar {.sidebar}
==========

```{r, child = "src/Rmd/sidebar.Rmd"}
```

Home {data-icon=fa-home}
=========

```{r}
```

Standings {data-icon=fa-trophy data-orientation=columns}
=========

```{r, child = "src/Rmd/standings.Rmd"}
```

Picks {data-icon=fa-sliders data-orientation=columns}
=========

```{r, child = "src/Rmd/picks.Rmd"}
```

Teams {data-icon=fa-table}
=========

```{r, child = "src/Rmd/teams.Rmd"}
```

Info {data-icon=fa-info-circle}
=========

```{r, child = "src/Rmd/info.Rmd"}
```
